# Generated by Django 5.0.6 on 2024-07-09 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="contact_people",
            field=models.ManyToManyField(
                related_name="contact_person_for_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="ContactPerson",
        ),
    ]
