# Generated by Django 5.0.6 on 2024-07-10 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_localgroup_contact_people_delete_contactperson"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localgroup",
            options={
                "verbose_name": "local group",
                "verbose_name_plural": "local groups",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "member", "verbose_name_plural": "members"},
        ),
        migrations.AlterField(
            model_name="localgroup",
            name="contact_people",
            field=models.ManyToManyField(
                related_name="contact_person_for_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contact people",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.TextField(verbose_name="cith"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.TextField(verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.TextField(verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="member_identifier",
            field=models.TextField(unique=True, verbose_name="member number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.TextField(verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="postal_code",
            field=models.TextField(verbose_name="postal code"),
        ),
    ]
