# Generated by Django 6.0.4 on 2026-06-07 15:37

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "member_identifier",
                    models.PositiveIntegerField(unique=True, verbose_name="member number"),
                ),
                ("first_name", models.TextField(verbose_name="first name")),
                ("last_name", models.TextField(verbose_name="last name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone_number", models.TextField(blank=True, verbose_name="phone number")),
                ("address", models.TextField(blank=True, verbose_name="address")),
                ("city", models.TextField(blank=True, verbose_name="city")),
                ("postal_code", models.TextField(blank=True, verbose_name="postal code")),
                (
                    "cadre",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the member is a cadre member.",
                        verbose_name="cadre",
                    ),
                ),
                (
                    "extra_information",
                    models.TextField(blank=True, verbose_name="Extra information"),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[("MEMBER", "Member"), ("SUPPORT", "Support member")],
                        default="MEMBER",
                        verbose_name="member type",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("nl", "Dutch"), ("en", "English")],
                        default="nl-NL",
                        help_text="User's preferred language for emails",
                        max_length=10,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Cancel membership below instead of deleting accounts.",
                        verbose_name="is registered",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "date_left",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date someone's membership was cancelled",
                        null=True,
                        verbose_name="date left",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.CreateModel(
            name="LocalGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "selectable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this group can be selected by new members signing up",
                        verbose_name="selectable",
                    ),
                ),
            ],
            options={
                "verbose_name": "local group",
                "verbose_name_plural": "local groups",
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="WorkGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "work group",
                "verbose_name_plural": "work groups",
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
