# Generated by Django 6.0.4 on 2026-06-07 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("members", "0001_initial"),
        ("membership", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credit_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="payments.account",
                verbose_name="credit account",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.membershiptier",
                verbose_name="membership tier",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.membershiptype",
                verbose_name="membership type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="LocalGroupMember",
            fields=[],
            options={
                "verbose_name": "local group member",
                "verbose_name_plural": "local group members",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.user",),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[],
            options={
                "verbose_name": "member",
                "verbose_name_plural": "members",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.user",),
        ),
        migrations.CreateModel(
            name="SupportMember",
            fields=[],
            options={
                "verbose_name": "support member",
                "verbose_name_plural": "support members",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.user",),
        ),
        migrations.AddField(
            model_name="localgroup",
            name="contact_people",
            field=models.ManyToManyField(
                blank=True,
                related_name="contact_person_for_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contact people",
            ),
        ),
        migrations.AddField(
            model_name="workgroup",
            name="workgroup_contact_people",
            field=models.ManyToManyField(
                blank=True,
                related_name="contact_person_for_working_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="contact people",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("email",), name="members_user_unique_email_key"
            ),
        ),
    ]
