# Generated by Django 5.1.10 on 2025-08-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cadre',
            field=models.BooleanField(default=False, help_text='Designates whether the member is a cadre member.', verbose_name='cadre'),
        ),
    ]
