# Generated by Django 6.0.6 on 2026-07-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('user_cancel_membership', 'Can cancel memberships')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
