# Generated by Django 5.1.10 on 2025-08-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_cadre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_information',
            field=models.TextField(blank=True, verbose_name='Extra information'),
        ),
    ]
