# Generated by Django 5.1.10 on 2025-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_cadre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_left',
            field=models.DateTimeField(blank=True, help_text="Date someone's membership was cancelled", null=True, verbose_name='date left'),
        ),
    ]
