# Generated by Django 5.1.11 on 2025-08-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_user_cadre"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="member_type",
            field=models.CharField(
                choices=[("MEMBER", "Member"), ("SUPPORT", "Support member")],
                default="MEMBER",
                verbose_name="membership type",
            ),
        ),
    ]
