# Generated by Django 5.1.11 on 2025-08-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_user_member_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[],
            options={
                "verbose_name": "member",
                "verbose_name_plural": "members",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.user",),
        ),
        migrations.CreateModel(
            name="SupportMember",
            fields=[],
            options={
                "verbose_name": "support member",
                "verbose_name_plural": "support members",
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.user",),
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
