# Generated by Django 5.1.10 on 2025-08-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_extra_information'),
        ('members', '0004_member_supportmember_alter_user_options'),
    ]

    operations = [
    ]
