# Generated by Django 5.1.11 on 2025-08-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_user_is_active"),
        ("members", "0004_member_supportmember_alter_user_options"),
    ]

    operations = []
