# Generated by Django 5.1.11 on 2025-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_merge_20250824_2130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Cancel membership below instead of deleting accounts.",
                verbose_name="is registered",
            ),
        ),
    ]
