# Generated by Django 5.1.11 on 2025-08-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_merge_20250824_2144"),
        ("members", "0006_alter_user_is_active"),
    ]

    operations = []
