# Generated by Django 5.2.6 on 2025-09-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_merge_20250828_0747"),
    ]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="selectable",
            field=models.BooleanField(
                default=True,
                help_text="Whether this group can be selected by new members signing up",
                verbose_name="selectable",
            ),
        ),
    ]
