# Generated by Django 5.2.7 on 2025-10-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_localgroup_selectable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="member_identifier",
            field=models.PositiveIntegerField(unique=True, verbose_name="member number"),
        ),
    ]
