# Generated by Django 5.2.7 on 2025-11-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_user_member_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGroupMember',
            fields=[
            ],
            options={
                'verbose_name': 'local group member',
                'verbose_name_plural': 'local group members',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.user',),
        ),
    ]
