# Generated by Django 6.0.2 on 2026-02-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_localgroupmember'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershiptype', verbose_name='membership type (tier)'),
        ),
    ]
