# Generated by Django 5.2.9 on 2026-02-08 13:37

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('members', '0010_localgroupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('workgroup_contact_people', models.ManyToManyField(blank=True, related_name='contact_person_for_working_groups', to=settings.AUTH_USER_MODEL, verbose_name='contact people')),
            ],
            options={
                'verbose_name': 'work group',
                'verbose_name_plural': 'work groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
