# Generated by Django 6.0.3 on 2026-03-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_workgroup'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershiptier', verbose_name='membership tier'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershiptype', verbose_name='membership type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SUPPORT', 'Support member')], default='MEMBER', verbose_name='member type'),
        ),
    ]
