# Generated by Django 6.0.4 on 2026-05-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('nl', 'Dutch'), ('en', 'English')], default='nl-NL', help_text="User's preferred language for emails", max_length=10, verbose_name='preferred language'),
        ),
    ]
