# Generated by Django 5.2.9 on 2026-02-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_user_membership_type'),
        ('membership', '0004_remove_membershiptype_minimum_custom_amount_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershiptier', verbose_name='membership tier'),
        ),
    ]
