# Generated by Django 6.0.3 on 2026-04-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_user_membership_tier_user_membership_type_and_more'),
        ('payments', '0003_alter_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payments.account', verbose_name='credit account'),
        ),
    ]
