# Generated by Django 5.2.9 on 2026-02-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_user_membership_tier'),
        ('membership', '0004_remove_membershiptype_minimum_custom_amount_cents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SUPPORT', 'Support member')], default='MEMBER', verbose_name='member type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershiptype', verbose_name='membership type'),
        ),
    ]
