# Generated by Django 6.0.4 on 2026-06-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_user_language"),
        ("members", "0013_user_credit_account"),
    ]

    operations = []
