repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: .*/static/.*
  - id: end-of-file-fixer
    exclude: .*/static/.*
  - id: debug-statements
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: name-tests-test
    args: [--django]
    exclude: .*/__mocks__.py
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.10
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
