[project]
name = "symfexit"
version = "0.1.0"
description = ""
authors = [
    {name = "Jelle Besseling", email = "jelle@pingiun.com"}
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: European Union Public Licence 1.2 (EUPL 1.2)",
]
dependencies = [
    "django ~= 5.0",
    "django-tailwind ~= 3.4",
    "django-constance ~= 3.1",
    "fontawesomefree ~= 6.2",
    "pillow ~= 10.0",
    "django-tinymce ~= 4.0",
    "mollie-api-python ~= 3.6",
    "psycopg ~= 3.2.0",
    "dj-database-url ~= 2.1",
    "hashids ~= 1.3",
]
requires-python = ">= 3.10"

optional-dependencies.dev = [
    "django-browser-reload ~= 1.6",
    "black",
    "isort",
    "pip-tools",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = false
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
