# Generated by Django 5.1.10 on 2025-08-24 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipapplication",
            name="preferred_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.localgroup",
                verbose_name="preferred group",
            ),
        ),
    ]
