# Generated by Django 5.1.11 on 2025-09-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0002_alter_membershipapplication_preferred_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershipapplication",
            name="_order",
        ),
    ]
