# Generated by Django 5.2.9 on 2026-02-17 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('signup', '0003_remove_membershipapplication__order'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.order', verbose_name='subscription order'),
        ),
    ]
