# Generated by Django 6.0.2 on 2026-02-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('signup', '0004_membershipapplication__order'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='membership_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershiptier', verbose_name='membership tier'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershiptype', verbose_name='membership type'),
        ),
    ]
