# Generated by Django 4.2.7 on 2023-11-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationPayment",
            fields=[
                (
                    "payable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.payable",
                    ),
                ),
            ],
            bases=("payments.payable",),
        ),
    ]
