# Generated by Django 5.0.6 on 2024-07-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_localgroup_options_alter_user_options_and_more"),
        ("signup", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationpayment",
            options={
                "verbose_name": "application payment",
                "verbose_name_plural": "application payments",
            },
        ),
        migrations.AlterModelOptions(
            name="membershipapplication",
            options={
                "verbose_name": "membership application",
                "verbose_name_plural": "membership applications",
            },
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="address",
            field=models.CharField(max_length=100, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="birth_date",
            field=models.DateField(verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="city",
            field=models.CharField(max_length=100, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="payment_amount",
            field=models.IntegerField(verbose_name="payment amount in cents"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="phone_number",
            field=models.CharField(max_length=100, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="postal_code",
            field=models.CharField(max_length=100, verbose_name="postal code"),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="preferred_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="members.localgroup",
                verbose_name="preferred group",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="created",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
