# Generated by Django 4.2.7 on 2024-04-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_remove_membership_id_remove_membership_user_and_more"),
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipapplication",
            name="_subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.membership",
            ),
        ),
        migrations.AlterField(
            model_name="membershipapplication",
            name="_payable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="signup.applicationpayment",
            ),
        ),
    ]
