# Generated by Django 4.2.7 on 2023-11-27 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0003_membershipapplication__payable"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
