# Generated by Django 4.2.7 on 2023-11-27 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("signup", "0004_membershipapplication_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="created",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="membershipapplication",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
