# Generated by Django 5.0.6 on 2024-07-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="address",
            field=models.CharField(max_length=100, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="city",
            field=models.CharField(max_length=100, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="postal_code",
            field=models.CharField(max_length=100, verbose_name="postal code"),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.billingaddress",
                verbose_name="billing address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="order",
            name="done_at",
            field=models.DateTimeField(null=True, verbose_name="done at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                max_length=100, null=True, verbose_name="payment method"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="created",
                max_length=10,
                verbose_name="payment status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="order",
            name="return_url",
            field=models.URLField(null=True, verbose_name="return URL"),
        ),
        migrations.AlterField(
            model_name="order",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="payments.subscription",
                verbose_name="subscription",
            ),
        ),
    ]
