# Generated by Django 4.2.7 on 2023-11-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payable",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="initial",
                max_length=10,
            ),
        ),
    ]
