# Generated by Django 4.2.7 on 2024-04-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="type",
        ),
    ]
