# Generated by Django 4.2.7 on 2023-11-27 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payable_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payable",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
