# Generated by Django 4.2.7 on 2023-11-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payable_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="payable",
            name="return_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="payable",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="created",
                max_length=10,
            ),
        ),
    ]
