# Generated by Django 5.0 on 2024-05-11 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_subscription_period_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingaddress",
            options={
                "verbose_name": "Billing address",
                "verbose_name_plural": "Billing addresses",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
