# Generated by Django 6.0.4 on 2026-06-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupFlags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "members_become_staff",
                    models.BooleanField(
                        help_text="Designates whether members of this group can log in to the administration",
                        verbose_name="Members become staff",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "group flags",
            },
        ),
        migrations.CreateModel(
            name="WellKnownPermissionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("view_all", "View all"),
                            ("contact_person", "Contact person"),
                            ("board", "Board"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="well_known_code",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "well known permission group",
                "verbose_name_plural": "well known permission groups",
            },
        ),
    ]
