# Generated by Django 5.2.7 on 2025-10-18 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_alter_wellknownpermissiongroup_group'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_become_staff', models.BooleanField(help_text='Designates whether members of this group can log in to the administration')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='auth.group')),
            ],
        ),
    ]
