# Generated by Django 5.2.7 on 2025-10-18 14:41

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_alter_wellknownpermissiongroup_group'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
            ],
            options={
                'permissions': [('members_become_staff', 'Members of this group become staff')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
