# Generated by Django 5.2.7 on 2025-11-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_groupflags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupflags',
            options={'verbose_name': 'group flags'},
        ),
        migrations.AlterModelOptions(
            name='wellknownpermissiongroup',
            options={'verbose_name': 'well known permission group', 'verbose_name_plural': 'well known permission groups'},
        ),
        migrations.AlterField(
            model_name='groupflags',
            name='members_become_staff',
            field=models.BooleanField(help_text='Designates whether members of this group can log in to the administration', verbose_name='Members become staff'),
        ),
        migrations.AlterField(
            model_name='wellknownpermissiongroup',
            name='code',
            field=models.CharField(choices=[('view_all', 'View all'), ('board', 'Board')], max_length=255, unique=True),
        ),
    ]
