# Generated by Django 5.2.7 on 2025-11-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_groupflags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellknownpermissiongroup',
            name='code',
            field=models.CharField(choices=[('view_all', 'View all'), ('contact_person', 'Contact person')], max_length=255, unique=True),
        ),
    ]
