# Generated by Django 4.2.7 on 2023-11-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0003_payable_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MolliePayment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("payment_id", models.CharField(max_length=100)),
                ("body", models.JSONField()),
                (
                    "payable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.payable",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["payment_id"], name="payments_mo_payment_1abcfa_idx"
                    )
                ],
            },
        ),
    ]
