# Generated by Django 5.0 on 2024-05-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments_mollie", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="molliepayment",
            old_name="payable",
            new_name="order",
        ),
    ]
