# Generated by Django 5.0.6 on 2024-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="args",
            field=models.BinaryField(blank=True, null=True, verbose_name="arguments"),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="completed at"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="identifier"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="kwargs",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="keyword arguments"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=20, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="output",
            field=models.TextField(blank=True, null=True, verbose_name="output"),
        ),
        migrations.AlterField(
            model_name="task",
            name="picked_up_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="picked up at"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("completed", "Completed"),
                    ("not_registered", "Unknown task (not registered)"),
                    ("exception", "Exception"),
                ],
                default="queued",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
