# Generated by Django 4.2.4 on 2023-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("completed", "Completed"),
                    ("not_registered", "Unknown task (not registered)"),
                    ("exception", "Exception"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
