# Generated by Django 5.0 on 2024-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="args",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="kwargs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
