# Generated by Django 6.0.2 on 2026-02-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_payment_transaction_paymentobligation_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('allow_custom_amount', models.BooleanField(default=False, verbose_name='allow custom amount')),
                ('minimum_custom_amount_cents', models.IntegerField(blank=True, null=True, verbose_name='minimum custom amount (cents)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
            ],
            options={
                'verbose_name': 'membership type',
                'verbose_name_plural': 'membership types',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.product', verbose_name='product')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='membership.membershiptype', verbose_name='membership type')),
            ],
            options={
                'verbose_name': 'membership tier',
                'verbose_name_plural': 'membership tiers',
                'ordering': ['membership_type', 'position'],
            },
        ),
    ]
