# Generated by Django 5.2.9 on 2026-02-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('payments', '0002_payment_transaction_paymentobligation_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='custom_amount_product',
            field=models.ForeignKey(blank=True, help_text='Product used when a member chooses a custom amount. Required when custom amount is allowed.', null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.product', verbose_name='custom amount product'),
        ),
    ]
