# Generated by Django 5.2.9 on 2026-02-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershiptype_custom_amount_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptier',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
    ]
