# Generated by Django 5.2.9 on 2026-02-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membershiptier_enabled_membershiptype_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='minimum_custom_amount_cents',
        ),
    ]
