# Generated by Django 4.2.7 on 2023-12-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TailwindKey",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Color"),
                            ("secondary", "Secondary Color"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("value", models.TextField()),
            ],
        ),
    ]
