# Generated by Django 4.2.4 on 2023-08-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TailwindKey",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Color"),
                            ("secondary", "Secondary Color"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("value", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="ColorKey",
        ),
    ]
