# Generated by Django 5.0.6 on 2024-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0002_alter_tailwindkey_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentThemeVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("version", models.DateField(auto_now=True)),
            ],
            options={
                "get_latest_by": "version",
            },
        ),
    ]
