# Generated by Django 5.0.6 on 2024-07-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0005_alter_tailwindkey_name_alter_tailwindkey_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currentthemeversion",
            name="version",
        ),
    ]
