# Generated by Django 5.0.6 on 2024-07-10 12:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "home page", "verbose_name_plural": "home pages"},
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="title",
            field=models.CharField(blank=True, max_length=50, verbose_name="Title"),
        ),
    ]
