# PVC for the app data, should allow multiple writers
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symfexit-data
  namespace: symfexit-staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfexit
  namespace: symfexit-staging
  labels:
    app: symfexit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: symfexit
  template:
    metadata:
      labels:
        app: symfexit
    spec:
      initContainers:
      - name: symfexit-migrations
        image: ghcr.io/roodjong/symfexit:main
        imagePullPolicy: Always
        args:
        - django-admin
        - migrate
        env:
        - name: DJANGO_ENV
          value: production
        - name: CONTENT_DIR
          value: /data
        - name: SYMFEXIT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: symfexit-secret
              key: secret_key
        - name: STATIC_ROOT
          value: /staticfiles
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: symfexit-pguser-symfexit
              key: pgbouncer-uri
      containers:
      - name: symfexit
        image: ghcr.io/roodjong/symfexit:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        args:
        - uvicorn
        - symfexit.asgi:application
        - --host
        - 0.0.0.0
        env:
        - name: DJANGO_ENV
          value: production
        - name: CONTENT_DIR
          value: /data
        - name: SYMFEXIT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: symfexit-secret
              key: secret_key
        - name: STATIC_ROOT
          value: /staticfiles
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: symfexit-pguser-symfexit
              key: pgbouncer-uri
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
        volumeMounts:
        - name: symfexit-data
          mountPath: /data
      volumes:
      - name: symfexit-data
        persistentVolumeClaim:
          claimName: symfexit-data
---
apiVersion: v1
kind: Service
metadata:
  name: symfexit
  namespace: symfexit-staging
spec:
  selector:
    app: symfexit
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
# Symfexit worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfexit-worker
  namespace: symfexit-staging
  labels:
    app: symfexit-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfexit-worker
  template:
    metadata:
      labels:
        app: symfexit-worker
    spec:
      containers:
      - name: symfexit-worker
        image: ghcr.io/roodjong/symfexit:main
        imagePullPolicy: Always
        args:
        - django-admin
        - startworker
        env:
        - name: DJANGO_ENV
          value: production
        - name: CONTENT_DIR
          value: /data
        - name: SYMFEXIT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: symfexit-secret
              key: secret_key
        - name: STATIC_ROOT
          value: /staticfiles
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: symfexit-pguser-symfexit
              key: pgbouncer-uri
        volumeMounts:
        - name: symfexit-data
          mountPath: /data
      volumes:
      - name: symfexit-data
        persistentVolumeClaim:
          claimName: symfexit-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: symfexit-nginx-config
  namespace: symfexit-staging
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    http {
      sendfile on;
      upstream symfexit {
        server symfexit:8000;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://symfexit;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $http_x_real_ip;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
          proxy_set_header X-Request-ID $http_x_request_id;
        }
        location /static/ {
          alias /staticfiles/;
        }
      }
      types {
        text/html                                        html htm shtml;
        text/css                                         css;
        text/xml                                         xml;
        image/gif                                        gif;
        image/jpeg                                       jpeg jpg;
        application/javascript                           js;
        application/atom+xml                             atom;
        application/rss+xml                              rss;

        text/mathml                                      mml;
        text/plain                                       txt;
        text/vnd.sun.j2me.app-descriptor                 jad;
        text/vnd.wap.wml                                 wml;
        text/x-component                                 htc;

        image/avif                                       avif;
        image/png                                        png;
        image/svg+xml                                    svg svgz;
        image/tiff                                       tif tiff;
        image/vnd.wap.wbmp                               wbmp;
        image/webp                                       webp;
        image/x-icon                                     ico;
        image/x-jng                                      jng;
        image/x-ms-bmp                                   bmp;

        font/woff                                        woff;
        font/woff2                                       woff2;

        application/java-archive                         jar war ear;
        application/json                                 json;
        application/mac-binhex40                         hqx;
        application/msword                               doc;
        application/pdf                                  pdf;
        application/postscript                           ps eps ai;
        application/rtf                                  rtf;
        application/vnd.apple.mpegurl                    m3u8;
        application/vnd.google-earth.kml+xml             kml;
        application/vnd.google-earth.kmz                 kmz;
        application/vnd.ms-excel                         xls;
        application/vnd.ms-fontobject                    eot;
        application/vnd.ms-powerpoint                    ppt;
        application/vnd.oasis.opendocument.graphics      odg;
        application/vnd.oasis.opendocument.presentation  odp;
        application/vnd.oasis.opendocument.spreadsheet   ods;
        application/vnd.oasis.opendocument.text          odt;
        application/vnd.openxmlformats-officedocument.presentationml.presentation
                                                        pptx;
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                                                        xlsx;
        application/vnd.openxmlformats-officedocument.wordprocessingml.document
                                                        docx;
        application/vnd.wap.wmlc                         wmlc;
        application/wasm                                 wasm;
        application/x-7z-compressed                      7z;
        application/x-cocoa                              cco;
        application/x-java-archive-diff                  jardiff;
        application/x-java-jnlp-file                     jnlp;
        application/x-makeself                           run;
        application/x-perl                               pl pm;
        application/x-pilot                              prc pdb;
        application/x-rar-compressed                     rar;
        application/x-redhat-package-manager             rpm;
        application/x-sea                                sea;
        application/x-shockwave-flash                    swf;
        application/x-stuffit                            sit;
        application/x-tcl                                tcl tk;
        application/x-x509-ca-cert                       der pem crt;
        application/x-xpinstall                          xpi;
        application/xhtml+xml                            xhtml;
        application/xspf+xml                             xspf;
        application/zip                                  zip;

        application/octet-stream                         bin exe dll;
        application/octet-stream                         deb;
        application/octet-stream                         dmg;
        application/octet-stream                         iso img;
        application/octet-stream                         msi msp msm;

        audio/midi                                       mid midi kar;
        audio/mpeg                                       mp3;
        audio/ogg                                        ogg;
        audio/x-m4a                                      m4a;
        audio/x-realaudio                                ra;

        video/3gpp                                       3gpp 3gp;
        video/mp2t                                       ts;
        video/mp4                                        mp4;
        video/mpeg                                       mpeg mpg;
        video/quicktime                                  mov;
        video/webm                                       webm;
        video/x-flv                                      flv;
        video/x-m4v                                      m4v;
        video/x-mng                                      mng;
        video/x-ms-asf                                   asx asf;
        video/x-ms-wmv                                   wmv;
        video/x-msvideo                                  avi;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfexit-nginx
  namespace: symfexit-staging
  labels:
    app: symfexit-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: symfexit-nginx
  template:
    metadata:
      labels:
        app: symfexit-nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/roodjong/symfexit:main
        imagePullPolicy: Always
        args:
        - nginx
        - -c
        - /etc/nginx/nginx.conf
        volumeMounts:
        - name: symfexit-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: symfexit-nginx-config
        configMap:
          name: symfexit-nginx-config
---
# Service for symfexit-nginx
apiVersion: v1
kind: Service
metadata:
  name: symfexit-nginx
  namespace: symfexit-staging
spec:
  selector:
    app: symfexit-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: symfexit-nginx
  namespace: symfexit-staging
spec:
  parentRefs:
    - name: eg
      namespace: default
  hostnames:
    - "symfexit-staging.yele.dev"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: symfexit-nginx
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
