# Generated by Django 5.1.1 on 2024-09-28 15:41

from datetime import datetime
from django.db import migrations, models


def get_time_millis() -> int:
    return int(datetime.now().timestamp() * 1000)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentThemeVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "version",
                    models.BigIntegerField(
                        default=get_time_millis,
                        unique=True,
                        verbose_name="version",
                    ),
                ),
            ],
            options={
                "get_latest_by": "version",
            },
        ),
        migrations.CreateModel(
            name="TailwindKey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Color"),
                            ("secondary", "Secondary Color"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                ("value", models.TextField(verbose_name="value")),
            ],
        ),
    ]
