# Generated by Django 5.1.6 on 2025-03-09 11:44

import symfexit.theme.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentThemeVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "version",
                    models.BigIntegerField(
                        default=symfexit.theme.utils.get_time_millis,
                        unique=True,
                        verbose_name="version",
                    ),
                ),
            ],
            options={
                "get_latest_by": "version",
            },
        ),
        migrations.CreateModel(
            name="TailwindKey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("color-primary", "Primary Color"),
                            ("color-secondary", "Secondary Color"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                ("value", models.TextField(verbose_name="value")),
            ],
        ),
    ]
