# Generated by Django 6.0.4 on 2026-06-07 15:37

import symfexit.theme.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentThemeVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "version",
                    models.BigIntegerField(
                        default=symfexit.theme.utils.get_time_millis,
                        unique=True,
                        verbose_name="version",
                    ),
                ),
            ],
            options={
                "get_latest_by": "version",
            },
        ),
        migrations.CreateModel(
            name="TailwindKey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin-color", "Admin Color"),
                            ("admin-color-headerbar", "Admin Header Bar Color"),
                            ("color-primary", "Primary Color"),
                            ("font-header", "Font used in the header"),
                        ],
                        max_length=80,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                ("value", models.TextField(verbose_name="value")),
            ],
        ),
    ]
