# Generated by Django 5.1.11 on 2025-08-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tailwindkey",
            name="name",
            field=models.CharField(
                choices=[
                    ("color-primary", "Primary Color"),
                    ("font-header", "Font used in the header"),
                ],
                max_length=20,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
