# Generated by Django 5.1.1 on 2024-11-24 13:48

import symfexit.theme.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentthemeversion",
            name="version",
            field=models.BigIntegerField(
                default=symfexit.theme.utils.get_time_millis, unique=True, verbose_name="version"
            ),
        ),
    ]
