# Generated by Django 5.2.7 on 2025-10-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theme", "0002_alter_tailwindkey_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tailwindkey",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin-color", "Admin Color"),
                    ("admin-color-headerbar", "Admin Header Bar Color"),
                    ("color-primary", "Primary Color"),
                    ("font-header", "Font used in the header"),
                ],
                max_length=80,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
