# Generated by Django 6.0.4 on 2026-06-07 15:37

import django.db.models.deletion
import symfexit.documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField(verbose_name="name")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "trashed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="trashed at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "filenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.filenode",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="folder_owner",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "directory",
                "verbose_name_plural": "directories",
            },
            bases=("documents.filenode",),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "filenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.filenode",
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        upload_to=symfexit.documents.models.file_location, verbose_name="content"
                    ),
                ),
                ("size", models.IntegerField(default=0, verbose_name="size")),
                (
                    "content_type",
                    models.TextField(
                        default="application/octet-stream", verbose_name="content type"
                    ),
                ),
            ],
            options={
                "verbose_name": "file",
                "verbose_name_plural": "files",
            },
            bases=("documents.filenode",),
        ),
        migrations.AddField(
            model_name="filenode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="documents.directory",
                verbose_name="parent directory",
            ),
        ),
        migrations.AddConstraint(
            model_name="filenode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("trashed_at__isnull", True)),
                fields=("parent", "name"),
                name="unique_sibling_names",
                nulls_distinct=False,
            ),
        ),
    ]
