# Generated by Django 5.1.1 on 2024-11-24 13:48

import symfexit.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.FileField(
                upload_to=symfexit.documents.models.file_location, verbose_name="content"
            ),
        ),
    ]
