# Generated by Django 5.1.11 on 2025-08-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="filenode",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="unique_sibling_names", nulls_distinct=False
            ),
        ),
    ]
