# Generated by Django 5.2.5 on 2025-08-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_filenode_unique_sibling_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="filenode",
            name="trashed_at",
            field=models.DateTimeField(null=True, verbose_name="trashed at"),
        ),
    ]
