# Generated by Django 5.2.5 on 2025-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_filenode_trashed_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="filenode",
            name="unique_sibling_names",
        ),
        migrations.AddConstraint(
            model_name="filenode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("trashed_at__isnull", True)),
                fields=("parent", "name"),
                name="unique_sibling_names",
                nulls_distinct=False,
            ),
        ),
    ]
