# Generated by Django 5.2.9 on 2026-02-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_filenode_unique_sibling_names_and_more'),
        ('members', '0011_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_owner', to='members.workgroup'),
        ),
        migrations.AlterField(
            model_name='filenode',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='trashed at'),
        ),
    ]
