# Generated by Django 5.2.9 on 2026-02-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0005_directory_owner_alter_filenode_trashed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_owner', to='auth.group'),
        ),
    ]
