# Generated by Django 5.2.7 on 2025-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('default', 'Default template'), ('welcome_email', 'Admin Color')], max_length=80, unique=True, verbose_name='template')),
                ('subject', models.TextField(verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
            ],
        ),
    ]
