# Generated by Django 5.2.7 on 2025-11-14 14:18

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLayout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('membership-application', 'Membership application template'), ('password-reset', 'Request new password template')], max_length=80, unique=True, verbose_name='template')),
                ('body', tinymce.models.HTMLField(verbose_name='body')),
                ('text_body', models.TextField(help_text="Text body is used for people who don't allow html in their emails.", verbose_name='text body')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('membership-application', 'Membership application template'), ('password-reset', 'Request new password template')], max_length=80, unique=True, verbose_name='template')),
                ('from_email', models.EmailField(max_length=254, verbose_name='from email')),
                ('subject', models.TextField(verbose_name='subject')),
                ('body', tinymce.models.HTMLField(verbose_name='body')),
                ('text_body', models.TextField(help_text="Text body is used for people who don't allow html in their emails.", verbose_name='text body')),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='emails.emaillayout', verbose_name='email layout')),
            ],
        ),
    ]
