# Generated by Django 5.2.7 on 2025-10-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('welcome_email', 'Welcome Email')], max_length=80, unique=True, verbose_name='template'),
        ),
    ]
