# Generated by Django 5.2.7 on 2025-11-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillayout',
            name='template',
            field=models.CharField(choices=[], max_length=80, verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[], max_length=80, unique=True, verbose_name='template'),
        ),
    ]
