# Generated by Django 5.2.7 on 2025-10-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_emailtemplate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(),
        ),
    ]
