# Generated by Django 5.2.7 on 2025-11-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_emaillayout_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillayout',
            name='template',
            field=models.CharField(choices=[('Layout template', 'layout')], max_length=80, verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('membership-application', 'Membership application template'), ('password-reset', 'Request new password template')], max_length=80, unique=True, verbose_name='template'),
        ),
    ]
