# Generated by Django 5.2.7 on 2025-10-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='text_body',
            field=models.TextField(default='', verbose_name='Text body'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('welcome', 'Welcome template'), ('apply', 'Apply template')], max_length=80, unique=True, verbose_name='template'),
        ),
    ]
