# Generated by Django 5.2.9 on 2026-03-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emaillayout_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('membership-application', 'Membership application template'), ('password-reset', 'Request new password template'), ('signup-accepted', 'Signup accepted template')], max_length=80, unique=True, verbose_name='template'),
        ),
    ]
