# Generated by Django 6.0.4 on 2026-05-25 13:31

import random
import math
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emaillayout_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillayout',
            name='name',
            field=models.CharField(default=lambda: str(random.randint(1, 1000000)), max_length=80, unique=True, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(choices=[('nl', 'Dutch'), ('en', 'English'), ('*', 'Fallback for missing languages')], default='*', help_text="Receiver's preferred language", max_length=10, verbose_name='preferred language'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('membership-application', 'Membership application template'), ('password-reset', 'Request new password template')], max_length=80, verbose_name='template'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('template', 'language')},
        ),
    ]
