# Generated by Django 5.2.7 on 2025-10-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailtemplate_text_body_alter_emailtemplate_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='from_email',
            field=models.EmailField(default='', max_length=254, verbose_name='From email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('layout', 'Layout template'), ('welcome', 'Welcome template'), ('apply', 'Apply template')], max_length=80, unique=True, verbose_name='template'),
        ),
    ]
