# Generated by Django 6.0.4 on 2026-06-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_alter_emailtemplate_template"),
        ("emails", "0004_emaillayout_name_emailtemplate_language"),
    ]

    operations = []
