# Generated by Django 6.0.5 on 2026-06-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_merge_20260607_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('membership-application', 'Membership application template'), ('password-reset', 'Request new password template'), ('signup-accepted', 'Signup accepted template')], max_length=80, verbose_name='template'),
        ),
    ]
