# Generated by Django 5.2.7 on 2025-10-25 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_emailtemplate_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLayout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('layout', 'Layout template')], max_length=80, unique=True, verbose_name='template')),
                ('body', models.TextField(verbose_name='body')),
                ('text_body', models.TextField(verbose_name='Text body')),
            ],
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.CharField(choices=[('welcome', 'Welcome template'), ('apply', 'Apply template')], max_length=80, unique=True, verbose_name='template'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='emails.emaillayout', verbose_name='email layout'),
        ),
    ]
