# Generated by Django 6.0.4 on 2026-06-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_name", models.CharField(verbose_name="name")),
                ("event_organiser", models.CharField(verbose_name="organiser")),
                ("event_date", models.DateTimeField(verbose_name="start date")),
                ("event_end", models.DateTimeField(blank=True, null=True, verbose_name="end date")),
                ("event_desc", models.TextField(verbose_name="description")),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
