# Generated by Django 5.1.10 on 2025-08-24 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_user_cadre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.TextField(verbose_name='location')),
                ('starts_at_date', models.DateField(verbose_name='starts at date')),
                ('starts_at_time', models.TimeField(verbose_name='starts at time')),
                ('ends_at_date', models.DateField(verbose_name='ends at')),
                ('ends_at_time', models.TimeField(verbose_name='ends at time')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='event creator')),
                ('organised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='members.localgroup', verbose_name='organized by')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
