# Generated by Django 6.0.4 on 2026-06-07 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="signed_up_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="attendees",
            ),
        ),
    ]
