# Generated by Django 5.2.7 on 2025-10-11 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ends_at_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ends_at_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starts_at_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starts_at_time',
        ),
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ends at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='starts at'),
            preserve_default=False,
        ),
    ]
