# Generated by Django 5.2.7 on 2025-12-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_organiser',
            field=models.CharField(default='organiser', verbose_name='event organiser'),
            preserve_default=False,
        ),
    ]
