# Generated by Django 5.2.7 on 2025-12-14 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_organiser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='signed_up_events', to=settings.AUTH_USER_MODEL, verbose_name='attendees'),
        ),
    ]
