# Generated by Django 5.2.7 on 2025-12-14 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_attendees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, editable=False, related_name='signed_up_events', to=settings.AUTH_USER_MODEL, verbose_name='attendees'),
        ),
    ]
