# Generated by Django 5.2.7 on 2025-12-14 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='end date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_desc',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_organiser',
            field=models.CharField(verbose_name='organiser'),
        ),
    ]
