# Generated by Django 5.1.6 on 2025-03-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, verbose_name="identifier"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                ("args", models.BinaryField(blank=True, null=True, verbose_name="arguments")),
                (
                    "kwargs",
                    models.BinaryField(blank=True, null=True, verbose_name="keyword arguments"),
                ),
                ("output", models.TextField(blank=True, verbose_name="output")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("completed", "Completed"),
                            ("not_registered", "Unknown task (not registered)"),
                            ("exception", "Exception"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "picked_up_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="picked up at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="tenants.client",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
