# Generated by Django 5.1.6 on 2025-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="output",
            field=models.TextField(blank=True, verbose_name="output"),
        ),
    ]
