# Generated by Django 5.1.6 on 2025-03-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("worker", "0002_alter_task_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tenants.client",
                verbose_name="tenant",
            ),
        ),
    ]
