# Generated by Django 5.0 on 2024-05-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "subscription_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "membership",
            },
            bases=("payments.subscription",),
        ),
    ]
