# Generated by Django 5.0.6 on 2024-07-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "verbose_name": "membership",
                "verbose_name_plural": "memberships",
            },
        ),
    ]
