# Generated by Django 4.2.7 on 2024-04-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_subscription_type"),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="id",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="valid",
        ),
        migrations.AddField(
            model_name="membership",
            name="subscription_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="payments.subscription",
            ),
            preserve_default=False,
        ),
    ]
