# Generated by Django 5.0 on 2024-05-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_remove_membership_id_remove_membership_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={"verbose_name": "Membership"},
        ),
    ]
