# Generated by Django 4.2.7 on 2023-12-03 21:16

import uuid

import django.db.models.deletion
from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "filenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.filenode",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Directories",
            },
            bases=("documents.filenode",),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "filenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.filenode",
                    ),
                ),
                ("content", models.FileField(upload_to=documents.models.file_location)),
                ("size", models.IntegerField(default=0)),
                ("content_type", models.TextField(default="application/octet-stream")),
            ],
            bases=("documents.filenode",),
        ),
        migrations.AddField(
            model_name="filenode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="documents.directory",
            ),
        ),
    ]
