# Generated by Django 4.1.4 on 2023-01-31 15:14

from django.db import migrations, models
import django.db.models.deletion
import documents.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="documents.filenode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "filenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.filenode",
                    ),
                ),
            ],
            bases=("documents.filenode",),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "filenode_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="documents.filenode",
                    ),
                ),
                ("content", models.FileField(upload_to=documents.models.file_location)),
            ],
            bases=("documents.filenode",),
        ),
    ]
