# Generated by Django 4.2.4 on 2023-08-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directory",
            options={"verbose_name_plural": "Directories"},
        ),
    ]
