# Generated by Django 5.0.6 on 2024-07-10 12:49

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="directory",
            options={"verbose_name": "directory", "verbose_name_plural": "directories"},
        ),
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "file", "verbose_name_plural": "files"},
        ),
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.FileField(
                upload_to=documents.models.file_location, verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="content_type",
            field=models.TextField(
                default="application/octet-stream", verbose_name="content type"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.IntegerField(default=0, verbose_name="size"),
        ),
        migrations.AlterField(
            model_name="filenode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="filenode",
            name="name",
            field=models.TextField(verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="filenode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="documents.directory",
                verbose_name="parent directory",
            ),
        ),
    ]
