# Generated by Django 4.2.7 on 2023-11-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_directory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content_type",
            field=models.TextField(default="application/octet-stream"),
        ),
        migrations.AddField(
            model_name="file",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="filenode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="documents.directory",
            ),
        ),
    ]
