# Generated by Django 6.0.3 on 2026-03-07 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MollieSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('test_api_key', models.CharField(blank=True, max_length=255)),
                ('live_mode', models.BooleanField(default=False)),
                ('payment_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mollie_settings', to='payments.paymentprovider')),
            ],
        ),
    ]
