# Generated by Django 6.0.4 on 2026-06-07 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MollieCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mollie_customer_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mollie_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MolliePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mollie_payment_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("mollie_customer_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="open", max_length=50)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mollie_payments",
                        to="payments.paymentobligation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MollieSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("test_api_key", models.CharField(blank=True, max_length=255)),
                ("live_mode", models.BooleanField(default=False)),
                (
                    "webhook_base_url",
                    models.CharField(
                        blank=True,
                        help_text="Base URL for webhooks when no request is available (e.g. https://example.com)",
                        max_length=255,
                    ),
                ),
                (
                    "payment_description",
                    models.CharField(
                        default="{product_name} - {member_number}",
                        help_text="Template for payment description. Available variables: {order_id}, {product_name}, {amount}, {member_number}",
                        max_length=255,
                    ),
                ),
                (
                    "payment_provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mollie_settings",
                        to="payments.paymentprovider",
                    ),
                ),
            ],
        ),
    ]
