# Generated by Django 5.1.1 on 2024-11-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mollie", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="molliepayment",
            new_name="mollie_moll_payment_02ad56_idx",
            old_name="payments_mo_payment_1abcfa_idx",
        ),
    ]
