# Generated by Django 5.1.11 on 2025-09-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mollie", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MolliePayment",
        ),
    ]
