# Generated by Django 5.2.9 on 2026-03-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mollie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molliesettings',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='molliesettings',
            name='test_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
