# Generated by Django 6.1.1 on 2026-10-04 17:43

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models


def link_payments(apps, schema_editor):
    """Find the Payments each already-booked MolliePayment created.

    record_receipt booked them (the part applied to the obligation and any
    surplus) on the same obligation, through the order's provider, into the
    provider's credit_to_account, right before processed_at was stamped.
    Payments that can't be matched stay unlinked; they just can't be refunded
    online.
    """
    MolliePayment = apps.get_model("mollie", "MolliePayment")
    Payment = apps.get_model("payments", "Payment")

    linked = set()
    mollie_payments = MolliePayment.objects.filter(processed_at__isnull=False).select_related(
        "obligation__order__paid_using"
    )
    for mp in mollie_payments.order_by("processed_at"):
        provider = mp.obligation.order.paid_using
        if provider is None:
            continue
        payments = Payment.objects.filter(
            obligation_id=mp.obligation_id,
            paid_using=provider,
            transaction__debit_account_id=provider.credit_to_account_id,
            created_at__gte=mp.processed_at - timedelta(minutes=1),
            created_at__lte=mp.processed_at,
        ).exclude(pk__in=linked)
        for payment in payments:
            mp.payments.add(payment)
            linked.add(payment.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("mollie", "0001_initial"),
        ("payments", "0003_order_cancellation_reason_paymentreversal"),
    ]

    operations = [
        migrations.AddField(
            model_name="molliepayment",
            name="payments",
            field=models.ManyToManyField(
                blank=True, related_name="mollie_payments", to="payments.payment"
            ),
        ),
        migrations.CreateModel(
            name="MollieReversal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mollie_id", models.CharField(max_length=255, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("refund", "Refund"), ("chargeback", "Chargeback")], max_length=20
                    ),
                ),
                ("amount_cents", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("chargeback_reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mollie_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reversals",
                        to="mollie.molliepayment",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payments.payment",
                    ),
                ),
                (
                    "payment_reversals",
                    models.ManyToManyField(
                        blank=True, related_name="mollie_reversals", to="payments.paymentreversal"
                    ),
                ),
            ],
        ),
        migrations.RunPython(link_payments, migrations.RunPython.noop),
    ]
