# Generated by Django 6.0.3 on 2026-03-08 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mollie', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolliePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_payment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='open', max_length=50)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mollie_payments', to='payments.paymentobligation')),
            ],
        ),
    ]
