# Generated by Django 6.0.3 on 2026-03-08 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mollie', '0002_molliepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='molliesettings',
            name='webhook_base_url',
            field=models.CharField(blank=True, help_text='Base URL for webhooks when no request is available (e.g. https://example.com)', max_length=255),
        ),
        migrations.CreateModel(
            name='MollieCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_customer_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mollie_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
