# Generated by Django 6.0.3 on 2026-03-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mollie', '0003_molliesettings_webhook_base_url_molliecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='molliepayment',
            name='mollie_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
