# Generated by Django 6.0.3 on 2026-03-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mollie', '0004_molliepayment_mollie_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='molliesettings',
            name='payment_description',
            field=models.CharField(default='{product_name} - {member_number}', help_text='Template for payment description. Available variables: {order_id}, {product_name}, {amount}, {member_number}', max_length=255),
        ),
    ]
