# Generated by Django 6.0.3 on 2026-04-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mollie', '0005_molliesettings_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='molliepayment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
