# Generated by Django 5.2.9 on 2026-02-08 17:37

import django.db.models.deletion
import symfexit.payments.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('credit_balance', models.BooleanField(help_text='Assets and expenses are increased with debits, decreased with credits. Liabilities, equity, and income are increased with credits, decreased with debits. Tick this if the account increases with credits. This makes sure the balance is shown correctly.')),
            ],
            options={
                'verbose_name': 'general ledger',
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(verbose_name='enabled')),
                ('sku', models.SlugField(max_length=100, verbose_name='product sku')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('price_euros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('subscription', 'Subscription')], default='subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(max_length=100, verbose_name='postal code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'billing address',
                'verbose_name_plural': 'billing addresses',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('credit_balance', models.BooleanField(help_text='Assets and expenses are increased with debits, decreased with credits. Liabilities, equity, and income are increased with credits, decreased with debits. Tick this if the account increases with credits. This makes sure the balance is shown correctly.')),
                ('general_ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.generalledger')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=100, verbose_name='product sku')),
                ('product_name', models.CharField(max_length=100, verbose_name='product name')),
                ('product_price_euros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subscription_period_unit', models.CharField(blank=True, choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')])),
                ('subscription_period', models.IntegerField(help_text='How many of the period unit before the subscription repeats.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ordered_for_billing_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.billingaddress')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.product')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pay_before', models.DateTimeField()),
                ('amount_euros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.order')),
                ('ordered_for_billing_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.billingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.order')),
                ('obligation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentobligation')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')])),
                ('period', models.IntegerField(help_text='How many of the period unit before the subscription repeats.')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscription'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=symfexit.payments.models.tigerbeetle_id, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.IntegerField()),
                ('part_of', models.UUIDField(default=symfexit.payments.models.tigerbeetle_id)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_transactions', to='payments.account')),
                ('debit_account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='debit_transactions', to='payments.account')),
            ],
        ),
    ]
