# Generated by Django 5.1.11 on 2025-09-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_delete_membership"),
        ("mollie", "0002_delete_molliepayment"),
        ("payments", "0001_initial"),
        ("signup", "0003_remove_membershipapplication__order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.DeleteModel(
            name="BillingAddress",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
