# Generated by Django 6.0.6 on 2026-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="product_type",
            field=models.CharField(
                choices=[("subscription", "Subscription")], default="subscription"
            ),
        ),
    ]
