# Generated by Django 5.1.1 on 2024-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="price_per_period",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
