# Generated by Django 6.0.3 on 2026-03-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
        ),
    ]
