# Generated by Django 5.1.11 on 2025-09-07 13:07

import django.db.models.deletion
import symfexit.payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0002_remove_order_address_remove_order_subscription_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sku", models.CharField(max_length=100, verbose_name="product name")),
                ("name", models.CharField(max_length=100, verbose_name="product name")),
                ("price", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("subscription", "Subscription")], default="subscription"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
        ),
        migrations.CreateModel(
            name="BillingAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("address", models.CharField(max_length=100, verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                ("postal_code", models.CharField(max_length=100, verbose_name="postal code")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "billing address",
                "verbose_name_plural": "billing addresses",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_sku", models.CharField(max_length=100, verbose_name="product name")),
                ("product_name", models.CharField(max_length=100, verbose_name="product name")),
                ("product_price", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_unit", models.CharField(verbose_name=symfexit.payments.models.PeriodUnit)),
                ("period", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payments.product"
                    ),
                ),
            ],
        ),
    ]
