# Generated by Django 6.1.1 on 2026-10-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_payment_order_order_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chargeback", "Chargeback"),
                    ("signup_rejected", "Membership application rejected"),
                ],
                default="",
                verbose_name="cancellation reason",
            ),
        ),
        migrations.CreateModel(
            name="PaymentReversal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("refund", "Refund"), ("chargeback", "Chargeback")],
                        verbose_name="reason",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obligation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.paymentobligation",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="payments.payment",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="payments.transaction"
                    ),
                ),
            ],
        ),
    ]
