# Generated by Django 5.2.9 on 2026-02-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
