# Generated by Django 5.1.11 on 2025-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="price_euros",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.SlugField(max_length=100, verbose_name="product sku"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="period",
            field=models.IntegerField(
                help_text="How many of the period unit before the subscription repeats."
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="period_unit",
            field=models.CharField(
                choices=[("day", "Day"), ("week", "Week"), ("month", "Month"), ("year", "Year")]
            ),
        ),
    ]
