# Generated by Django 6.0.3 on 2026-04-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_account_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('code__in', [16110]), _negated=True), fields=('code',), name='account_code_unique_when_not_shared'),
        ),
    ]
