# Generated by Django 5.1.11 on 2025-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_remove_product_price_product_price_euros_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="enabled",
            field=models.BooleanField(default=False, verbose_name="enabled"),
            preserve_default=False,
        ),
    ]
