# Generated by Django 5.2.9 on 2026-03-07 10:40

import django.db.models.deletion
import symfexit.payments.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_payment_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='credit_to_account',
            field=models.ForeignKey(default=symfexit.payments.models.default_bank_account_uuid, on_delete=django.db.models.deletion.PROTECT, to='payments.account'),
        ),
    ]
