# Generated by Django 5.1.11 on 2025-09-07 16:30

import symfexit.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_account_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                default=symfexit.payments.models.tigerbeetle_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
