# Generated by Django 5.2.9 on 2026-03-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_paid_using_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
