# Generated by Django 5.1.11 on 2025-09-08 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="credit_normal",
            new_name="credit_balance",
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
