# Generated by Django 5.2.9 on 2026-03-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentprovider_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_using',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentprovider'),
        ),
    ]
