# Generated by Django 5.1.11 on 2025-09-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_rename_credit_normal_account_credit_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="code",
            field=models.SlugField(max_length=80),
            preserve_default=False,
        ),
    ]
