# Generated by Django 5.2.9 on 2026-03-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_order_paid_using'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
