# Generated by Django 5.1.11 on 2025-09-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_account_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
