# Generated by Django 5.1.11 on 2025-09-14 09:43

from django.db import migrations

ACCOUNT_ACCOUNTS_RECEIVABLE = 13011
ACCOUNT_REVENUE = 82811

def create_default_accounts(apps, schema_editor):
    Account = apps.get_model("payments", "Account")
    Account.objects.get_or_create(
        code=ACCOUNT_REVENUE,
        defaults={
            "name": "Revenue",
            "description":
                "Membership revenue balance account. In RGS this is mapped to WLbeLbvLbv (82811). See: https://www.boekhoudplaza.nl/rgs_rekeningen/WLbeLbvLbv&KB=R&kzB=SVC&rgsv=WLbeLbvLbv/Ledenbetalingen_inclusief_reeds_betaalde_voorschotten.htm",
            "credit_balance": True,
        },
    )
    Account.objects.get_or_create(
        code=ACCOUNT_ACCOUNTS_RECEIVABLE,
        defaults={
            "name": "Accounts Receivable",
            "description":
                "Accounts receivable represents money owed by entities to the firm on the sale of products or services on credit. In RGS this is mapped to BVorDebHad (13011). See: https://www.boekhoudplaza.nl/rgs_rekeningen/BVorDebHad&KB=R&kzB=SVC/Debiteuren.htm",
            "credit_balance": False,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_account_code_alter_account_credit_balance_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_accounts)
    ]
