# Generated by Django 5.2.6 on 2025-09-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_initial_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="credit_account",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="debit_account",
            field=models.UUIDField(),
        ),
    ]
