# Generated by Django 5.2.6 on 2025-09-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_alter_transaction_credit_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="credit_account",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="credit_transactions",
                to="payments.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="debit_account",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="debit_transactions",
                to="payments.account",
            ),
        ),
    ]
