# Generated by Django 5.2.6 on 2025-09-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_alter_transaction_credit_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="billing_method",
            field=models.CharField(
                choices=[("leading", "leading"), ("trailing", "trailing")], default="leading"
            ),
        ),
    ]
