# Generated by Django 5.2.6 on 2025-10-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_subscription_billing_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='billing_method',
        ),
    ]
