# Generated by Django 5.2.6 on 2025-10-11 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_remove_subscription_billing_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_price_euros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_period',
            field=models.IntegerField(default=1, help_text='How many of the period unit before the subscription repeats.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_period_unit',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='product_sku',
            field=models.CharField(max_length=100, verbose_name='product sku'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.product'),
        ),
    ]
