# Generated by Django 5.2.6 on 2025-10-11 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_order_product_price_order_ordered_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_for_billing_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.billingaddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
