# Generated by Django 5.2.7 on 2025-10-18 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_order_ordered_for_billing_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="subscription_period",
            field=models.IntegerField(
                help_text="How many of the period unit before the subscription repeats.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subscription_period_unit",
            field=models.CharField(
                blank=True,
                choices=[("day", "Day"), ("week", "Week"), ("month", "Month"), ("year", "Year")],
            ),
        ),
        migrations.CreateModel(
            name="PaymentObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("period", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payments.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("paid_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payments.order"
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.paymentobligation",
                    ),
                ),
            ],
        ),
    ]
