# Generated by Django 5.2.7 on 2025-10-18 12:21

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_order_created_at_alter_order_subscription_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentobligation",
            name="pay_before",
            field=models.DateTimeField(
                default=timezone.now,
            ),
            preserve_default=False,
        ),
    ]
