# Generated by Django 5.2.7 on 2025-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_paymentobligation_pay_before"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentobligation",
            name="amount_euros",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
