# Generated by Django 5.2.7 on 2025-10-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0021_paymentobligation_amount_euros"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentobligation",
            name="ordered_for_billing_address",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="payments.billingaddress"
            ),
            preserve_default=False,
        ),
    ]
