# Generated by Django 5.2.7 on 2026-02-08 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_paymentobligation_ordered_for_billing_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('credit_balance', models.BooleanField(help_text='Assets and expenses are increased with debits, decreased with credits. Liabilities, equity, and income are increased with credits, decreased with debits. Tick this if the account increases with credits. This makes sure the balance is shown correctly.')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='general_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.generalledger'),
        ),
    ]
