# Generated by Django 5.2.9 on 2026-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_generalledger_account_general_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalledger',
            options={'verbose_name': 'general ledger'},
        ),
        migrations.AddField(
            model_name='generalledger',
            name='code',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
