# Generated by Django 5.2.7 on 2026-02-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payments_time_zone',
            field=models.CharField(default='Europe/Amsterdam', max_length=100),
        ),
    ]
