# Generated by Django 6.0.3 on 2026-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='homepage_current',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='logo_image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='main_site',
            field=models.URLField(blank=True, default='https://roodjongeren.nl/'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_tiers_json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='site_title',
            field=models.CharField(blank=True, default='Membersite', max_length=100, null=True),
        ),
    ]
