# Generated by Django 5.2.9 on 2026-03-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_payments_time_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='payments_time_zone',
            new_name='payments_timezone',
        ),
    ]
