# Generated by Django 6.0.3 on 2026-04-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_config'),
        ('tenants', '0002_client_payments_timezone'),
    ]

    operations = [
    ]
