name: Lints

on:
  push:
    branches: [ "main" ]
  pull_request:


jobs:
  python-checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - '3.13'
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv and set the Python version
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Ruff linter
      run: |
        uv run --frozen ruff check
    - name: Ruff format check
      run: |
        uv run --frozen ruff format --check
