name: Update lock.json
on:
  push:
    branches:
      - dependabot/pip/**
  pull_request:
    branches:
      - dependabot/pip/**
  workflow_dispatch: # allows manual triggering

jobs:
  lockfile:
    name: Commit new lock.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Relock dependencies after requirements.txt change
        run: |
          nix run '.#relock-dependencies'
      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: "[dependabot skip] Relock dependencies"
          branch: ${{ github.head_ref }}
