name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:


jobs:
  django-checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - '3.12'
          - '3.13'

    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv and set the Python version
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Run Tests
      run: |
        uv run --frozen python manage.py test
    - name: Run Django Check
      run: |
        uv run --frozen python manage.py check
    - name: Check migrations
      run: |
        uv run --frozen python manage.py makemigrations --check
