name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:


jobs:
  django-checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - '3.13'
          - '3.14'

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:17
        # Provide the password for postgres
        env:
          POSTGRES_USER: symfexit
          POSTGRES_DB: symfexit
          POSTGRES_PASSWORD: symfexit
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v5
    - name: Install the latest version of uv and set the Python version
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Run Tests
      run: |
        uv run --frozen python manage.py test
      env:
        DATABASE_URL: postgres://symfexit:symfexit@localhost:5432/symfexit
    - name: Run Django Check
      run: |
        uv run --frozen python manage.py check
    - name: Check migrations
      run: |
        uv run --frozen python manage.py makemigrations --check
      env:
        DATABASE_URL: postgres://symfexit:symfexit@localhost:5432/symfexit
